# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ec2Fuzzysearch < Formula
  desc "Fuzzy search aws ec2 instance"
  homepage "https://github.com/mickeey2525/ec2-fuzzysearch"
  version "0.0.5"

  on_macos do
    on_intel do
      url "https://github.com/mickeey2525/ec2-fuzzysearch/releases/download/0.0.5/ec2-fuzzysearch_Darwin_x86_64.tar.gz"
      sha256 "b1681ffcc7e8fe1f4ecd17e32b974d5607f833ad6a8d89e869718edac5ea2110"

      def install
        bin.install "ec2-fuzzysearch"
      end
    end
    on_arm do
      url "https://github.com/mickeey2525/ec2-fuzzysearch/releases/download/0.0.5/ec2-fuzzysearch_Darwin_arm64.tar.gz"
      sha256 "e04d2ffb29566b6944e08c99aba5d87a51d33cd88edc7305ac622e2bc091d7d0"

      def install
        bin.install "ec2-fuzzysearch"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mickeey2525/ec2-fuzzysearch/releases/download/0.0.5/ec2-fuzzysearch_Linux_x86_64.tar.gz"
        sha256 "e7d2c27d5dfcede505fe3597a234adc0d594259a19ac78bcc1784edc738847b0"

        def install
          bin.install "ec2-fuzzysearch"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mickeey2525/ec2-fuzzysearch/releases/download/0.0.5/ec2-fuzzysearch_Linux_arm64.tar.gz"
        sha256 "47743b35edd4e42cde46471db66c633b40c41a2b56b845dd727cdff8c708c36e"

        def install
          bin.install "ec2-fuzzysearch"
        end
      end
    end
  end
end
